CREATE TABLE SETTORI (
    ID SMALLINT AUTO_INCREMENT PRIMARY KEY,
    nomeSettore VARCHAR(128) NOT NULL UNIQUE
);


CREATE TABLE STIPULE (
    ID SMALLINT AUTO_INCREMENT PRIMARY KEY,
    vigente DATE NOT NULL,
    deccorenza DATE NOT NULL,
    scadenza DATE NOT NULL,
    partiStipulanti TINYTEXT NOT NULL,
    settore SMALLINT,
    FOREIGN KEY(settore) REFERENCES SETTORI(ID) ON DELETE CASCADE ON UPDATE CASCADE,

    -- TESTI
    RE_MINIMI_CONTRATTUALI TEXT,
    RE_PREMIO_RISULTATO TEXT,
    RE_ALTRE_VOCI TEXT,
    APP_PROFESSIONALIZANTE TEXT,
    APP_ALTRE_TIPOLOGIE TEXT,
    WELF_PREVIDENZA_COMPLEMENTARE TEXT,
    WELF_ASSISTENZA_INTEGRATIVA TEXT,
    WELF_ENTI_BILATERALI TEXT,
    WELF_POLIZZE_ASSICURATIVE TEXT,
    NOTE TEXT,
    FOREIGN KEY(settore) REFERENCES SETTORI(ID) ON DELETE CASCADE ON UPDATE CASCADE
);


CREATE INDEX settori_stipule ON STIPULE(settore);


CREATE TABLE RETRIBUZIONI (
    ID SMALLINT AUTO_INCREMENT PRIMARY KEY,
    livello VARCHAR(3) NOT NULL,
    nomeColonne VARCHAR(32) NOT NULL,
    tipologia char(2) NOT NULL,
    stipula SMALLINT,
    importo DOUBLE NOT NULL,

    -- TESTI
    commento TEXT,
    FOREIGN KEY(stipula) REFERENCES STIPULE(ID) ON DELETE CASCADE ON UPDATE CASCADE
);


CREATE INDEX stipule_retributive ON RETRIBUZIONI(stipula);


CREATE TABLE APRENDISTATI (
    ID SMALLINT AUTO_INCREMENT PRIMARY KEY,
    livello VARCHAR(3) NOT NULL,
    inizio TINYINT NOT NULL,
    fine TINYINT NOT NULL,
    condizione DATE,
    livello_target VARCHAR(3) NOT NULL,
    stipula SMALLINT,
    -- TESTI
    commento TEXT,
    FOREIGN KEY(stipula) REFERENCES STIPULE(ID) ON DELETE CASCADE ON UPDATE CASCADE
);


CREATE TABLE APRENDISTATI_PERC (
    ID SMALLINT AUTO_INCREMENT PRIMARY KEY,
    livello VARCHAR(3) NOT NULL,
    inizio TINYINT NOT NULL,
    fine TINYINT NOT NULL,
    condizione DATE,
    percentuale TINYINT NOT NULL,
    stipula SMALLINT,

    -- TESTI
    commento TEXT,
    FOREIGN KEY(stipula) REFERENCES STIPULE(ID) ON DELETE CASCADE ON UPDATE CASCADE
);