CREATE TABLE SETTORI (
    ID INT(3) AUTO_INCREMENT PRIMARY KEY,
    nomeSettore VARCHAR(32) NOT NULL UNIQUE
);

CREATE TABLE STIPULE (
    ID INT(4) AUTO_INCREMENT PRIMARY KEY,
    deccorenza DATE NOT NULL,
    scadenza DATE NOT NULL,
    partiStipulanti VARCHAR(128) NOT NULL,
    settore INT(3),
    tipologia char(1) NOT NULL,
    FOREIGN KEY(settore) REFERENCES SETTORI(ID) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE RETRIBUZIONI (
    ID INT(4) AUTO_INCREMENT PRIMARY KEY,
    livello VARCHAR(3) NOT NULL,
    nomeColonne VARCHAR(32) NOT NULL,
    stipula INT(4),
    importo DOUBLE NOT NULL,
    FOREIGN KEY(stipula) REFERENCES STIPULE(ID) ON DELETE CASCADE ON UPDATE CASCADE
);